apiVersion: v1 
kind: Pod
metadata:
  name: kube-practice
  labels:
    name: kube-practice
    type: front-end

spec:
  containers: #this is an array
  - name: kube-practice # - tells that this is the first element in this list , we cannot use camel case here
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 40
