apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app:  myapp
    name: production
    ammar:  farooqi
spec:
  # this section is unique for every kind i.e. kind is Pod here so we will initialize containers here
  #in yaml list is identifid by - and containers is a list here

  #error below because limits are not mentioned
  containers: 
    - name: nginx-container
      image: nginx