apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-rc
  labels:
    name: replication-controller-example
    app: myapp
    type: front-end
spec:
#here below goes the pod definition which should be managed by replication controller
  template:
      metadata:
        name: myapp-pod
        labels:
          app:  myapp
          name: production
          ammar:  farooqi
      spec:
        # this section is unique for every kind i.e. kind is Pod here so we will initialize containers here
        #in yaml list is identifid by - and containers is a list here

        #error below because limits are not mentioned
        containers: 
          - name: nginx-container
            image: nginx
  replicas: 2
