apiVersion: v1
kind: Service
metadata:
  name: backend-service
  app:  myapp
  type: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app:  myapp
    type: backend-service